image: Ubuntu  # образ для сборки

stack: jdk 11

branches:
  only:
    - main  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  - java -jar ./artifacts/app-card-delivery.jar &


build_script:
  - ./gradlew test --info "-Dselenide.headless=true"
  - chmod +x gradlew